[package]
name = "order-book-service"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.68"
futures-util = "0.3.25"
tokio = { version = "1.24.0", features = ["full"] }
tokio-tungstenite = { version = "0.18.0", features = ["native-tls"] }
url = "2.3.1"
