name: Rust

on:
  push:
    branches: [ "main" ]
    paths-ignore: "**.md"
  pull_request:
    branches: [ "main" ]
    paths-ignore: "**.md"


env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install Protoc
      uses: arduino/setup-protoc@v1
    - uses: actions/checkout@v3
    - name: Build server
      run: cd service && cargo build -p "order-book-service-server" --verbose
    - name: Build client
      run: cd service && cargo build -p "order-book-service-client" --verbose
    - name: Run tests
      run: cd service && cargo test --verbose
    - name: Run clippy
      run: cd service && cargo clippy --all-targets -- --deny warnings
