name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Move into service
      run: cd service
    - name: Build server
      run: cargo build -p "order-book-service-server" --verbose
    - name: Build client
      run: cargo build -p "order-book-service-client" --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Run clippy
      run: cargo clippy --all-targets --deny-warnings
